[package]
name = "enviame"
version = "1.0.7"
edition = "2024"
license = "AGPL-3.0-only"
build = "build.rs"

[dependencies]
axum = "0.8"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sqlx = { version = "0.8", features = ["postgres", "runtime-tokio-native-tls", "time"] }
lettre = { version = "0.11", features = ["smtp-transport", "tokio1-native-tls"] }
dotenvy = "0.15"
tower-http = { version = "0.6", features = ["cors"] }
rand = "0.9"
reqwest = { version = "0.12", features = ["json"] }
axum_csrf = { version = "0.11", features = ["layer"] }
askama = "0.13"
anyhow = "1.0"
time = { version = "0.3", features = ["formatting"] }
sha2 = "0.10"
hmac = "0.12"
hex = "0.4"
once_cell = "1.21"
rust-embed = "8.7"
mime_guess = "2.0"

[build-dependencies]
html-minifier = "5.0"

[profile.release-prod]
inherits = "release"
lto = "fat"
strip = "debuginfo"
