[package]
name = "enviame"
version = "1.0.5"
edition = "2024"
license = "GPL-3.0"

[dependencies]
axum = "0.8"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sqlx = { version = "0.8", features = ["postgres", "runtime-tokio-native-tls", "time"] }
lettre = { version = "0.11", features = ["smtp-transport", "tokio1-native-tls"] }
dotenvy = "0.15"
tower-http = { version = "0.6", features = ["cors", "fs"] }
rand = "0.9.0"
reqwest = { version = "0.12.15", features = ["json"] }
chrono = "0.4.40"
axum_csrf = { version = "0.11.0", features = ["layer"] }
tracing-subscriber = "0.3.19"
askama = "0.13.0"
html-minifier = "5.0.0"
anyhow = "1.0.97"
time = { version = "0.3.41", features = ["formatting"] }
sha2 = "0.10.8"
hmac = "0.12.1"
hex = "0.4.3"
