[package]
name = "enviame"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.7"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sqlx = { version = "0.7", features = ["postgres", "runtime-tokio-native-tls"] }
jsonwebtoken = "9"
argon2 = "0.5"
lettre = { version = "0.11", features = ["smtp-transport", "tokio1-native-tls"] }
dotenvy = "0.15"
tower-http = { version = "0.5", features = ["cors"] }
rand = "0.9.0"
reqwest = { version = "0.12.15", features = ["json"] }
