version: 2.1
jobs:
  test-rust:
    docker:
      - image: cimg/rust:1.86.0
    steps:
      - checkout
      - restore_cache:
          key: cargo-{{ checksum "Cargo.lock" }}
      - run:
          command: cargo test
      - save_cache:
          key: cargo-{{ checksum "Cargo.lock" }}
          paths:
            - ~/.cargo
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: deploy
          command: '#e.g. ./deploy.sh'
      - run:
          name: found github actions config
          command: ':'
workflows:
  build-and-test:
    jobs:
      - test-rust
    # - deploy:
    #     requires:
    #       - test-rust
